// Locale URL prefixes — the content-directory codes under src/content/pages/<lang>/.
// Must match LANGUAGE_MAP in the translation scripts and the langCodes in mainNav.json.
export const LOCALE_CODES = [
  "ar",
  "bg",
  "zh-hans",
  "zh-hant",
  "fr",
  "de",
  "el",
  "hu",
  "id",
  "it",
  "ja",
  "ko",
  "ms",
  "fa",
  "pl",
  "pt-br",
  "pt-pt",
  "es",
  "es-419",
  "th",
  "tr",
  "vi",
];

/** The locale prefix of the current path, or null when on the default (English) site. */
export function getCurrentLocale(pathname: string): string | null {
  const first = pathname.split("/").filter(Boolean)[0];
  return first && LOCALE_CODES.includes(first) ? first : null;
}

// UI label dictionary: { "<English label>": { "<locale>": "<translation>" } }.
// Generated by scripts/translate-ui-strings.mjs from the nav/footer/sidebar data.
import uiStrings from "@data/i18n/ui.json";

/** Translate a UI label into the given locale, falling back to the original text. */
export function localizeText(text: unknown, locale: string | null): unknown {
  if (!locale || typeof text !== "string") return text;
  const entry = (uiStrings as Record<string, Record<string, string>>)[text];
  return (entry && entry[locale]) || text;
}

/**
 * Deep-translate all string label values in a nav/footer/sidebar data object using the
 * UI dictionary. Strings not in the dictionary (paths, URLs, component names, codes)
 * pass through unchanged, so it's safe to run over the whole structure.
 */
export function localizeData<T>(data: T, locale: string | null): T {
  if (!locale) return data;
  if (typeof data === "string") return localizeText(data, locale) as T;
  if (Array.isArray(data)) return data.map((d) => localizeData(d, locale)) as unknown as T;
  if (data && typeof data === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(data)) out[k] = localizeData(v, locale);
    return out as T;
  }
  return data;
}

/**
 * Prefix an internal link with the current locale so navigation stays in-language.
 * Leaves external links, protocol-relative URLs, anchors, mailto/tel, and
 * already-localized paths untouched. On the default (English) site, returns href as-is.
 */
export function localizePath(
  href: string | undefined | null,
  pathname: string
): string | undefined | null {
  const locale = getCurrentLocale(pathname);
  if (!locale || typeof href !== "string") return href;
  if (!href.startsWith("/") || href.startsWith("//")) return href; // external / protocol-relative
  const first = href.split("/").filter(Boolean)[0];
  if (first && LOCALE_CODES.includes(first)) return href; // already localized
  return `/${locale}${href}`;
}
